version: '3'

services:
  backend:
    build: ./Backend
    command: sh -c "uvicorn main:app --reload --port=8005 --host=0.0.0.0"
    ports:
      - "8005:8005"
    depends_on:
      - frontend

  frontend:
    build: ./Frontend
    ports:
      - "3000:3000"
